
version: 2

models:
  
  - name: stg_jaffle_shop_customers
    description: "A staging area for customers"
    columns:
      - name: customer_id
        description: "The primary key for this table"
        
  - name: stg_jaffle_shop_orders
    description: "A staging area for orders"
    columns:
      - name: order_id
        description: "The primary key for this table"
  
  - name: stg_stripe_payment
    description: "A staging area for payments"
    columns:
      - name: payment_id
        description: "The primary key for this table"

  - name: customer
    description: "A starter dbt model"
    
